### ISSUE TITLE
Autotools

### ISSUE THREAD

**Issue by lockie** [HolyBlackCat/quasi-msys2#11]
Hey, do you think it is possible to use autotools with quasi-msys2? I've tried `make install _autotools`, but it throws an error since it is just metapackage dependant on other packages like `autoconf`, `automake` etc, all without the prefix (`mingw-w64-ucrt`), so one cannot install them separately by hand.

**Comment by HolyBlackCat** [comment]
@lockie I'm not very familiar with autotools. What if you install the regular Linux autotools outside of quasi-msys2? Or is there something special about the ones shipped by msys2?

If the Linux autotools don't work, you can try running msys2 in a Windows VM, installing the packages you want, then copying the installaton directory to the Linux machine. If this ends up being useful, I can add a way of downloading those packages directly from quasi-msys2.

**Comment by HolyBlackCat** [comment]
Closing this for now, I'm assuming that linux autotools will be good enough. If it turns out they aren't, please tell.
