### ISSUE TITLE
Could the pacman be used, if this is hosted by Arch Linux?

### ISSUE THREAD

**Issue by dmikushin** [HolyBlackCat/quasi-msys2#12]
@HolyBlackCat , this IS a brilliant work!

I wonder how exactly the Cygwin dependency prevents from using MSYS-blessed pacman? Can we build a native pacman? Can we even use the system-based pacman, if the host system is Arch Linux?

**Comment by HolyBlackCat** [comment]
At least one person in MSYS2 discord claims that the native `pacman` on Arch can work with MSYS2 repos.

**Comment by HolyBlackCat** [comment]
Closing this for now, it's not something I'm planning to do at the moment.
