### ISSUE TITLE
Any containerization yet?

### ISSUE THREAD

**Issue by dmikushin** [HolyBlackCat/quasi-msys2#13]
Hi @HolyBlackCat ,

Do you or anyone work on bringing quiasi-msys2 into a container, Docker or Singularity?

**Comment by HolyBlackCat** [comment]
I haven't considered it. Why run in docker instead of directly in the host?

The scripts don't touch anything outside of the installation directory, and only a handful of dependencies need to be installed.

**Comment by HolyBlackCat** [comment]
Closing this for now, because I don't see any benefit this brings. If there is some benefit I'm not aware of, please tell.

**Comment by dmikushin** [comment]
The main benefit is that the software building containers for CI can be developed, starting from your base container.

**Comment by adalisk-emikhaylov** [comment]
@dmikushin What would my base container include? Just having the dependencies installed from the system package manager, plus a copy of the repository cloned, doesn't sound very useful. You could do it yourself in ~3 lines of code.

Or do you also want some of the MSYS2 packages to be baked into the container? But then it's a question of what to bake, and how to automatically update the container when MSYS2 updates their packages. Overall, it looks easier to me if every user that wants this in CI maintains their own CI image.

Also, I'm curious, why would you cross-compile in CI instead having it build directly on Windows? Is there any performance benefit to building on Linux, or something else.

**Comment by HolyBlackCat** [comment]
@dmikushin What would my base container include? Just having the dependencies installed from the system package manager, plus a copy of the repository cloned, doesn't sound very useful. You could do it yourself in ~3 lines of code.

Or do you also want some of the MSYS2 packages to be baked into the container? But then it's a question of what to bake, and how to automatically update the container when MSYS2 updates their packages. Overall, it looks easier to me if every user that wants this in CI maintains their own CI image.

Also, I'm curious, why would you cross-compile in CI instead having it build directly on Windows? Is there any performance benefit to building on Linux, or something else.

<sup>(sorry, posted from wrong account, reposting again)</sup>

**Comment by dmikushin** [comment]
> Also, I'm curious, why would you cross-compile in CI instead having it build directly on Windows?

We simply don't want to spin Windows machine for our product, it's to heavy to have it.

Your work is similar to https://github.com/mstorsjo/llvm-mingw and https://github.com/mstorsjo/msvc-wine . The value that you really add on top of this is handling additional dependencies via MSYS2.

> Or do you also want some of the MSYS2 packages to be baked into the container?

So yes, it would be awesome to have the full cross-compiler fully baked into container as @mstorsjo does, but also have an option to install additional MSYS2 packages.

**Comment by HolyBlackCat** [comment]
@dmikushin 

> We simply don't want to spin Windows machine for building our product, it's too heavy to have it.

I see, fair enough.

> So yes, it would be awesome to have the full cross-compiler fully baked into container

I see. What I don't want is having to continuously regenerate the image every time MSYS2 updates one of the packages I'd include, which would likely happen often. Currently quasi-msys2 just works and requires minimal maintenance from my side, I like this.

Plus, there are some customization options, and I'm not sure what would be the good defaults (like, do I include Wine or not? normally you don't need it, but sometimes you do).

I think it's easier if you do the installation directly in your dockerfile (or equivalent). Summarizing the readme, assuming Ubuntu, that would be something like:

```sh
sudo apt install git make wget tar zstd gpg wine
git clone https://github.com/HolyBlackCat/quasi-msys2
cd quasi-msys2
make install _gcc

# Latest clang: (or take an older one from apt)
bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"

# Symlink for compatibility (running interactively will tell you that you should create this)
sudo ln -nfs /path/to/quasi-msys2/ucrt64/root/ucrt64 /ucrt64
```
Then build as `bash -c 'source env/all.src && some_command'`.

There are a few options you can tweak, like not installing Wine if you don't need it (which also changes the build command a bit). Ask if you need help with those things.

**Comment by snoweuph** [comment]
I mean, this sounds to me like common CI, setting up a feature matrix in an github action.
Making it a cron task, so github runs it every few day/weeks, and inside the action just push them with fitting names, combined out of the features into the github container registry.

Im currently trying to cross compile a Rust GTK4 Application that utilized gettext for translations to windows.

Im also building my needed env in a Dockerfile, though its not completley working as expected yet
```dockerfile
FROM fedora:41

RUN dnf install -y \
  git \
  make \
  wget \
  tar \
  zstd \
  gawk \
  gpg \
  which \
  wine \
  llvm \
  clang \
  lld \
  ucrt64-gcc \
  cmake \
  meson

RUN curl \
  --proto '=https' \
  --tlsv1.2 \
  -sSf https://sh.rustup.rs \
  | sh -s -- -y

ENV PATH="/root/.cargo/bin:$PATH"

RUN cd / \
  && git clone https://github.com/holyblackcat/quasi-msys2

RUN ln -nfs "/quasi-msys2/root/ucrt64" /ucrt64

RUN cd /quasi-msys2 \
  && make install \
    _gcc \
    _gdb \
    mingw-w64-ucrt-x86_64-libadwaita \
    mingw-w64-ucrt-x86_64-gettext

RUN sh -c 'source /quasi-msys2/env/all.src && rustup target add $CARGO_BUILD_TARGET'

WORKDIR /app
CMD ["/quasi-msys2/env/shell.sh"]
```
