### ISSUE TITLE
make as the package manager app name is weird/confusing, how about  pkman, 

### ISSUE THREAD

**Issue by qingfengxia** [HolyBlackCat/quasi-msys2#2]

**Comment by HolyBlackCat** [comment]
`make` is not something I wrote or named. It's [a build system](https://en.wikipedia.org/wiki/Make_(software)), which I'm abusing as a scripting language. The code of the package manager in the file named `Makefile`, which `make` automatically finds in the current directory and interprets.

Also, `env/shell.sh` makes `pacmake` an alias for the package manager, accessible from any directory (which I think is a sufficiently punny name).
