### ISSUE TITLE
MSYS coreutils

### ISSUE THREAD

**Issue by lockie** [HolyBlackCat/quasi-msys2#7]
Hey, is there a way to install MSYS coreutils? The build process I'm trying to run requires target cat (or rather `cat.exe`). Trying to install coreuitls I get
```
# make install coreutils
Makefile:440: *** Unknown package or package alias: 'coreutils'.  Stop.
Makefile:902: *** Unable to execute `make  -r __database_nodeps __database_allow_aliases PKG@@coreutils`, exit code 2.  Stop.
```

**Comment by HolyBlackCat** [comment]
@lockie If you manually copy `cat.exe` from a Windows MSYS2 installation, is Wine able to run it? Last time I checked, executables belonging to the [`MSYS` environment](https://www.msys2.org/docs/environments/) (aka from packages not prefixed with `mingw-w64-`) didn't work.

Currently there's no way of installing packages from the MSYS environment, but if `cat.exe` ends up working for you, I can add support for that.

**Comment by lockie** [comment]
I haven't tried the one from MSYS2; ended up replacing cat with [bat](https://github.com/sharkdp/bat) instead (`cat.exe` from GnuWin32 was giving me weird-ass errors about input being the same as output).
